### ISSUE TITLE
GadgetListFragment

### ISSUE THREAD

**Issue by jmatj** [raphiz/gadgeothek#18]

**Comment by Excape** [comment]
- [ListView Guide](https://developer.android.com/guide/topics/ui/layout/listview.html)
- [Material Design Guide](https://material.google.com/components/lists.html)
- [Example ListView](https://github.com/HSR-MGE/W04-CustomArrayAdapterDemo/blob/master/app/src/main/java/com/example/listdemo/MainActivity.java)
- [Example with fragments](http://stackoverflow.com/questions/29464153/listview-in-fragment-context-menu)
- [ArrayAdapter](https://developer.android.com/reference/android/widget/ArrayAdapter.html)

**Comment by Excape** [comment]
TODO: Optimierung mit Tags
