### ISSUE TITLE
Meldung bei leerer Liste anzeigen

### ISSUE THREAD

**Issue by Excape** [raphiz/gadgeothek#23]
Ein layout für einen Hinweis wurde erstellt: 
`gadgetview_empty_reservations.xml`

Allerdings funktioniert das Einbinden des Layouts für eine leere Liste noch nicht. Bisheriger Versuch:

``` java
View emptyLayout = inflater.inflate(R.layout.gadgetview_empty_reservations, null);
gadgetListView.setEmptyView(emptyLayout);
gadgetListView.setAdapter(new GadgetItemAdapter(gadgetList));
populateListView();
....
```

**Comment by raphiz** [comment]
Fixed in b857efd
